---

# Copyright 2024 (c) José Ángel de Bustos Pérez 
#   Author: José Ángel de Bustos Pérez <jadebustos@gmail.com>
#
# This file is part of the IdM workshop.
#
# IdM workshop is free software: you can redistribute it and/or modify it under the terms of 
# the GNU General Public License v3 as published by the Free Software Foundation.
# IdM workshop is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License v3 for more details.

# You should have received a copy of the GNU General Public License v3 along with the IdM workshop. 
# If not, see https://www.gnu.org/licenses/gpl-3.0.en.html.

- name: install rpms
  ansible.builtin.dnf:
    name: "{{ rpms_general }}"
    state: latest

- name: enable chronyd service
  ansible.builtin.systemd:
    name: chronyd
    state: started
    masked: no
    enabled: true

- name: add ip address to all hosts to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4['address'] }} {{ item }} {{ hostvars[item].ansible_hostname }}"
    state: present
  when: hostvars[item].ansible_hostname is defined
  loop: "{{ groups.all }}"
